// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ReceiptsIDPointsGet implements GET /receipts/{id}/points operation.
//
// Returns the points awarded for the receipt.
//
// GET /receipts/{id}/points
func (UnimplementedHandler) ReceiptsIDPointsGet(ctx context.Context, params ReceiptsIDPointsGetParams) (r ReceiptsIDPointsGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReceiptsProcessPost implements POST /receipts/process operation.
//
// Submits a receipt for processing.
//
// POST /receipts/process
func (UnimplementedHandler) ReceiptsProcessPost(ctx context.Context, req *Receipt) (r ReceiptsProcessPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
