// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ReceiptsIDPointsGet implements GET /receipts/{id}/points operation.
	//
	// Returns the points awarded for the receipt.
	//
	// GET /receipts/{id}/points
	ReceiptsIDPointsGet(ctx context.Context, params ReceiptsIDPointsGetParams) (ReceiptsIDPointsGetRes, error)
	// ReceiptsProcessPost implements POST /receipts/process operation.
	//
	// Submits a receipt for processing.
	//
	// POST /receipts/process
	ReceiptsProcessPost(ctx context.Context, req *Receipt) (ReceiptsProcessPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
