// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

func encodeReceiptsIDPointsGetResponse(response ReceiptsIDPointsGetRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *ReceiptsIDPointsGetOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *NotFound:
		w.WriteHeader(404)

		span.SetStatus(codes.Error, http.StatusText(404))
		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeReceiptsProcessPostResponse(response ReceiptsProcessPostRes, w http.ResponseWriter, span trace.Span) error {
	switch response := response.(type) {
	case *ReceiptsProcessPostOK:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)
		span.SetStatus(codes.Ok, http.StatusText(200))

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *BadRequest:
		w.WriteHeader(400)
		span.SetStatus(codes.Error, http.StatusText(400))

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
